// MARK: - Libation
// Pharmacological and symbolic input that modifies both the practitioner's state
// and the ritual outcome space. Libation uniquely modifies the practitioner, not just the ritual.
// Each libation type is archaeologically attested.

/// The type of liquid offering poured during ritual.
public enum LibationType: String, Codable, Hashable, CaseIterable, Sendable {
    case water            // baseline — clean, neutral
    case fermentedWine    // knowledge and stability — the common offering
    case ritualMixture    // wine + Syrian rue + water lily — Sheol perception at cost of control
    case bloodOffering    // strength at cost of corruption — the dangerous offering
    case honeyWine        // sovereign maintenance — the royal offering
    case mimicBlood       // lower-cost substitute for blood — detection risk
    case opiumTincture    // ecstatic contact with recently dead — Tel Yehud vessels — severe variance
}

/// A libation prepared for ritual use.
public struct Libation: Codable, Hashable, Sendable {
    public let type: LibationType

    public init(_ type: LibationType) {
        self.type = type
    }

    /// Domain affinity of this libation type.
    public var domain: Domain? {
        switch type {
        case .water:          return nil            // neutral
        case .fermentedWine:  return .knowledge     // clarity, stability
        case .ritualMixture:  return .death         // Sheol-adjacent perception
        case .bloodOffering:  return .war           // strength, violence
        case .honeyWine:      return .rule          // sovereignty, maintenance
        case .mimicBlood:     return .war           // echoes blood, weaker
        case .opiumTincture:  return .faith         // ecstatic, devotional
        }
    }

    /// Resonance bonus contributed by this libation.
    public var resonanceModifier: Double {
        switch type {
        case .water:          return 0.0    // baseline — no bonus, no penalty
        case .fermentedWine:  return 0.15   // mild stability bonus
        case .ritualMixture:  return 0.25   // strong resonance, high risk
        case .bloodOffering:  return 0.3    // powerful but corrupting
        case .honeyWine:      return 0.2    // steady, reliable
        case .mimicBlood:     return 0.15   // weaker blood echo
        case .opiumTincture:  return 0.35   // strongest resonance, wildest variance
        }
    }

    /// Corruption generated by this libation.
    public var corruptionCost: Double {
        switch type {
        case .water:          return 0.0
        case .fermentedWine:  return 0.01
        case .ritualMixture:  return 0.05
        case .bloodOffering:  return 0.15
        case .honeyWine:      return 0.02
        case .mimicBlood:     return 0.08
        case .opiumTincture:  return 0.10
        }
    }

    /// Variance multiplier — how much this libation widens the outcome space.
    /// Higher variance = more extreme results in both directions.
    public var varianceMultiplier: Double {
        switch type {
        case .water:          return 1.0    // no additional variance
        case .fermentedWine:  return 0.85   // reduces variance — stabilizing
        case .ritualMixture:  return 1.8    // significant variance increase
        case .bloodOffering:  return 1.5    // moderate variance increase
        case .honeyWine:      return 0.9    // slightly stabilizing
        case .mimicBlood:     return 1.3    // moderate variance
        case .opiumTincture:  return 2.5    // extreme variance — wildcard
        }
    }

    /// Whether this libation gates access to higher tiers.
    public var tiersUnlocked: Set<SpiritTier> {
        switch type {
        case .water:          return [.common]
        case .fermentedWine:  return [.common, .uncommon]
        case .ritualMixture:  return [.common, .uncommon, .rare]
        case .bloodOffering:  return [.common, .uncommon, .rare]
        case .honeyWine:      return [.common, .uncommon, .rare, .legendary]
        case .mimicBlood:     return [.common, .uncommon]
        case .opiumTincture:  return [.common, .uncommon, .rare]
        }
    }
}
